# Generated by Django 5.0.2 on 2024-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
